[package]
name = "tarkov_pricing_overlay"
version = "0.1.0"
authors = ["John Schmidt <john@john2143.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version="0.11", features=["blocking", "json", "multipart", "stream"] }
image = "0.23.12"
inputbot = "0.5.0"
once_cell = "1.5.2"
libc = "0.2.82"
scrap = "0.5.0"
base64 = "0.13.0"
serde = {version="1.0.118", features=["derive"] }
serde_json = "1.0.61"
num-format = "0.4.0"
rayon = "1.5.0"
druid = "0.7.0"
