[package]
name = "tarkov_pricing_overlay"
version = "0.1.0"
authors = ["John Schmidt <john@john2143.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.10.10"
image = "0.23.12"
inputbot = "0.5.0"
once_cell = "1.5.2"
libc = "0.2.82"
scrap = "0.5.0"
